### ISSUE TITLE
Review Request

### ISSUE THREAD

**Issue by mcnamarabrian** [mcnamarabrian/pycon2023#8]
At this point I have the foundation of the things I want to highlight in this repo - local dev, local interaction, local testing, and deployment. I need to work on observability.

Please run through the project and ensure its correctness and offer thoughts on flow.

**Comment by djfurman** [comment]
I like the general flow and the attention to detail in the Makefile. I think it helps significantly reducing the barrier to entry.

The layers approach is certainly a best practice, but it did cause me a few issues my first run through. I'm going to start with a fresh repo and PR any ReadMe changes that it took me to correct it.

**Comment by djfurman** [comment]
Local dev and local testing are great highlight points, and the pipenv commands are nicely encapsulated. May want to consider adding a requirements generator into the Makefile? That way if attendees want to start expanding by bringing in their favorite dependencies they can easily have SAM build the local enhancements.

**Comment by mcnamarabrian** [comment]
Good call, @djfurman . I added the `generate-requirements` Make target to push [packages] in the `Pipfile` to the requirements.txt of each function.
